Feature/sc 534
meaningfy-ws/sem-covid pull request #239
Opened 2021-09-20 13:00 UTC by DanCh11

2021-09-20 14:31 UTC, costezki approved these changes
does this work now?

2021-09-20 14:32 UTC, costezki requested changes
I see tests failing. Can you please check those?

2021-09-22 08:20 UTC, Dragos0000 approved these changes

2021-09-22 08:21 UTC, Dragos0000 approved these changes

2021-09-22 08:23 UTC, Dragos0000 approved these changes

2021-09-22 08:24 UTC, Dragos0000 approved these changes

2021-09-22 08:48 UTC, costezki approved these changes
are we sure we want to pass title for content?

2021-09-22 08:48 UTC, costezki commented on tests/unit/dags/test_crawl_pipeline.py
> +fake_content_path_key = 'title'
it is strange to see the title passed as content.

2021-09-22 08:48 UTC, merged