Feature/sc 467
meaningfy-ws/sem-covid pull request #293
Opened 2021-12-21 18:15 UTC by CaptainOfHacks

2021-12-21 19:15 UTC, costezki requested changes
the tests are failing, they need a fix.

2022-01-03 12:50 UTC, Dragos0000 approved these changes

2022-01-10 20:43 UTC, costezki approved these changes

2022-01-10 20:43 UTC, costezki commented on sem_covid/adapters/rml_mapper.py
> +class RMLMapperABC(ABC):
Need some documentation.

2022-01-10 20:43 UTC, costezki commented on sem_covid/adapters/rml_mapper.py
> +
document, purpose and usage.

2022-01-10 20:43 UTC, costezki commented on sem_covid/entrypoints/etl_dags/rml_transform_dag.py
> +    "retry_delay": timedelta(minutes=3600),
2.5 days? That is a bit too much :)

2022-01-10 20:43 UTC, costezki commented on sem_covid/services/dataset_pipelines/rml_transform_pipeline.py
> +
Documentation :)

2022-01-10 20:43 UTC, costezki commented on sem_covid/services/dataset_pipelines/similarity_matrix_rml_transformation_pipeline.py
> +        number_of_parts = int(round(df_size / part_size, 0)) + 1
Drop `round` and `int` and use `//` floor division operator instead.

2022-01-10 20:43 UTC, costezki commented on sem_covid/services/dataset_pipelines/similarity_matrix_rml_transformation_pipeline.py
> +        number_of_parts = int(round(df_size / part_size, 0)) + 1
number_of_parts = len(self.dataset) // DATASET_PART_SIZE +1

2022-01-10 20:43 UTC, costezki commented on sem_covid/services/dataset_pipelines/similarity_matrix_rml_transformation_pipeline.py
> +        assert self.rdf_results is not None
:)

2022-01-10 20:43 UTC, costezki commented on sem_covid/services/dataset_pipelines/similarity_matrix_rml_transformation_pipeline.py
> +        self.extract()
:) We really need to switch to a proper ETL architecture in Airflow :)

2022-01-11 19:33 UTC, merged